'use client'

import { motion, useReducedMotion } from 'framer-motion'
import { ArrowUpRight, Github, Linkedin, Instagram, Mail, Code2, PenTool, Sparkles, Gamepad2, Menu, X } from 'lucide-react'
import { useState } from 'react'
import Link from 'next/link'

const projects = [
 {name:'LUMINA',category:'Social Platform',desc:'A web-first social experience where messages become interactive journeys instead of simple text delivery.',tech:['Next.js','TypeScript','Supabase','Framer Motion']},
 {name:'Invitation Studio',category:'Web Application',desc:'A customizable digital invitation platform for weddings, birthdays, and special events.',tech:['Next.js','React','Supabase']},
 {name:'Game Project',category:'Game Development',desc:'An experimental RPG experience exploring expressive game UI and interactive systems.',tech:['Godot','TypeScript','WebGL']},
 {name:'Creative Experiments',category:'Interactive Design',desc:'A collection of experimental interfaces, animations, and creative coding projects.',tech:['React','Motion','Figma']}
]
const skills=[['Frontend',['React','Next.js','TypeScript','Tailwind CSS']],['Backend',['Node.js','Supabase','PostgreSQL']],['Design',['Figma','UI/UX','Motion Design']],['Game',['Godot','Game UI','Interactive Systems']]]
const services=[['01',Code2,'Web Development','Fast, thoughtful websites and digital products built to feel as good as they perform.'],['02',PenTool,'UI/UX Design','Interfaces with strong hierarchy, clear interaction, and a distinctive visual language.'],['03',Sparkles,'Interactive Experiences','Motion-rich experiments and digital experiences that reward curiosity.'],['04',Gamepad2,'Game Development','Game interfaces and interactive systems with a focus on feel and usability.']]

function Reveal({children,delay=0}:{children:React.ReactNode,delay?:number}){const reduce=useReducedMotion();return <motion.div initial={reduce?false:{opacity:0,y:24}} whileInView={reduce?undefined:{opacity:1,y:0}} viewport={{once:true,margin:'-80px'}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Nav(){const [open,setOpen]=useState(false);return <header className="fixed top-0 z-50 w-full border-b border-white/[.06] bg-[#08090c]/70 backdrop-blur-xl"><div className="container flex h-20 items-center justify-between"><Link href="#" className="text-sm font-extrabold tracking-[.2em]">YOUR NAME<span className="text-indigo-400">.</span></Link><nav className="hidden gap-8 text-sm text-zinc-400 md:flex"><a href="#work" className="hover:text-white">Work</a><a href="#about" className="hover:text-white">About</a><a href="#services" className="hover:text-white">Services</a><a href="#contact" className="hover:text-white">Contact</a></nav><button aria-label="Toggle menu" className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="border-t border-white/[.06] px-5 py-5 md:hidden"><div className="container flex flex-col gap-5 text-zinc-300"><a href="#work" onClick={()=>setOpen(false)}>Work</a><a href="#about" onClick={()=>setOpen(false)}>About</a><a href="#services" onClick={()=>setOpen(false)}>Services</a><a href="#contact" onClick={()=>setOpen(false)}>Contact</a></div></nav>}</header>}
function Button({children,href='#'}:{children:React.ReactNode,href?:string}){return <motion.a whileHover={{y:-2}} whileTap={{scale:.98}} href={href} className="group inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-black">{children}<ArrowUpRight size={16} className="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></motion.a>}

export default function Home(){return <main className="noise overflow-hidden"><Nav/><section className="grid-bg relative min-h-screen pt-32"><div className="container grid min-h-[calc(100vh-8rem)] items-center gap-14 pb-20 lg:grid-cols-[1.1fr_.9fr]"><div><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{duration:.5}} className="mono mb-6 flex items-center gap-2 text-xs text-zinc-400"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_14px_#4ade80]"/> AVAILABLE FOR FREELANCE PROJECTS</motion.div><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.1}} className="max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[6.7rem]">Building Digital Experiences <span className="gradient-text">That Feel Different.</span></motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.45,duration:.7}} className="mt-7 max-w-xl text-base leading-7 text-zinc-400 sm:text-lg">Creative developer focused on building modern websites, interactive experiences, and digital products.</motion.p><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.6}} className="mt-9 flex flex-wrap gap-3"><Button href="#work">View My Work</Button><a href="#contact" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm font-bold hover:border-white/25">Contact Me <ArrowUpRight size={16}/></a></motion.div></div><div className="relative mx-auto h-[390px] w-full max-w-[500px] sm:h-[500px]"><div className="orb absolute left-1/2 top-1/2 h-64 w-64 -translate-x-1/2 -translate-y-1/2 rounded-full sm:h-80 sm:w-80"/><div className="absolute inset-8 rounded-[32px] border border-white/[.07]"/><div className="absolute right-0 top-16 glass rounded-2xl p-4 shadow-2xl"><div className="mono text-[10px] text-zinc-500">SYSTEM / 001</div><div className="mt-2 text-sm font-semibold">Ideas → Reality</div></div><div className="absolute bottom-16 left-0 glass rounded-2xl p-4"><div className="text-xs text-zinc-500">CURRENT FOCUS</div><div className="mt-1 text-sm font-semibold">Creative systems</div></div><div className="absolute inset-0 rounded-full border border-indigo-400/10 animate-[spin_24s_linear_infinite]"/></div></div></section>
<section id="about" className="border-t border-white/[.06] py-28"><div className="container grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><Reveal><div className="mono text-xs text-indigo-300">01 / ABOUT</div><h2 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-6xl">About Me</h2></Reveal><div><Reveal><p className="max-w-2xl text-xl leading-9 text-zinc-300">I'm a creative developer who combines technology, design, and storytelling to create digital experiences that are functional, memorable, and visually distinctive.</p></Reveal><div className="mt-14 grid grid-cols-3 gap-5 border-t border-white/[.08] pt-8">{[['05+','Projects'],['03+','Years Experience'],['10+','Technologies']].map(([n,l],i)=><Reveal key={l} delay={i*.08}><div><div className="text-3xl font-extrabold sm:text-4xl">{n}</div><div className="mt-2 text-xs text-zinc-500">{l}</div></div></Reveal>)}</div></div></div></section>
<section id="work" className="border-t border-white/[.06] py-28"><div className="container"><Reveal><div className="mono text-xs text-indigo-300">02 / SELECTED WORK</div><h2 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-6xl">Selected Work</h2></Reveal><div className="mt-14 grid gap-5 md:grid-cols-2">{projects.map((p,i)=><Reveal key={p.name} delay={i*.07}><article className="group rounded-3xl border border-white/[.08] bg-[var(--surface)] p-3 transition-all duration-500 hover:-translate-y-1 hover:border-indigo-300/20"><div className="grid-bg relative flex aspect-[16/10] items-end overflow-hidden rounded-2xl bg-[#0b0d12]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(123,112,255,.2),transparent_35%)] transition-transform duration-700 group-hover:scale-110"/><div className="relative p-6"><span className="mono text-[10px] text-zinc-500">0{i+1} / {p.category.toUpperCase()}</span><h3 className="mt-2 text-3xl font-bold">{p.name}</h3></div></div><div className="p-5"><p className="max-w-lg text-sm leading-6 text-zinc-400">{p.desc}</p><div className="mt-5 flex flex-wrap gap-2">{p.tech.map(t=><span key={t} className="rounded-full border border-white/[.08] px-3 py-1.5 text-[11px] text-zinc-400">{t}</span>)}</div><div className="mt-6 flex items-center justify-between"><a href="#contact" className="group/btn inline-flex items-center gap-2 text-sm font-semibold">View Project <ArrowUpRight size={15} className="transition-transform group-hover/btn:translate-x-1 group-hover/btn:-translate-y-1"/></a><Github size={17} className="text-zinc-600"/></div></div></article></Reveal>)}</div></div></section>
<section className="border-t border-white/[.06] py-28"><div className="container"><Reveal><div className="mono text-xs text-indigo-300">03 / TOOLKIT</div><h2 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-6xl">Tools I Work With</h2></Reveal><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{skills.map(([cat,items],i)=><Reveal key={cat as string} delay={i*.06}><div className="rounded-2xl border border-white/[.08] p-6"><div className="text-xs font-semibold uppercase tracking-widest text-zinc-500">{cat as string}</div><div className="mt-6 space-y-3">{(items as string[]).map(x=><div key={x} className="text-sm text-zinc-200">{x}</div>)}</div></div></Reveal>)}</div></div></section>
<section className="border-t border-white/[.06] py-28"><div className="container grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><Reveal><div className="mono text-xs text-indigo-300">04 / EXPERIENCE</div><h2 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-6xl">Experience</h2></Reveal><div className="space-y-0">{[['Creative Developer','Independent / Selected Projects','2023 — Present','Building experimental products across web, design, and interactive systems.'],['Digital Designer','Independent Practice','2022 — 2023','Exploring interface design, visual systems, and motion for digital products.']].map((e,i)=><Reveal key={e[0]} delay={i*.1}><div className="grid gap-3 border-t border-white/[.08] py-8 sm:grid-cols-[.8fr_1.2fr]"><div><div className="font-bold">{e[0]}</div><div className="mt-1 text-sm text-zinc-500">{e[1]}</div></div><div><div className="mono text-xs text-zinc-500">{e[2]}</div><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-400">{e[3]}</p></div></div></Reveal>)}</div></div></section>
<section id="services" className="border-t border-white/[.06] py-28"><div className="container"><Reveal><div className="mono text-xs text-indigo-300">05 / SERVICES</div><h2 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-6xl">What I Can Build</h2></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-white/[.08] bg-white/[.08] sm:grid-cols-2">{services.map(([num,Icon,title,desc],i)=><Reveal key={title as string} delay={i*.06}><div className="group bg-[var(--surface)] p-7 transition hover:bg-[var(--surface-2)] sm:p-9"><div className="flex items-start justify-between"><span className="mono text-xs text-zinc-600">{num as string}</span><Icon size={21} className="text-zinc-500 transition group-hover:text-indigo-300"/></div><h3 className="mt-14 text-xl font-bold">{title as string}</h3><p className="mt-3 max-w-md text-sm leading-6 text-zinc-500">{desc as string}</p></div></Reveal>)}</div></div></section>
<section id="contact" className="border-t border-white/[.06] py-28"><div className="container"><div className="relative overflow-hidden rounded-[32px] border border-white/[.08] bg-[var(--surface)] px-7 py-16 text-center sm:px-12 sm:py-24"><div className="absolute left-1/2 top-0 h-64 w-64 -translate-x-1/2 -translate-y-1/2 rounded-full bg-indigo-500/10 blur-3xl"/><Reveal><div className="mono text-xs text-indigo-300">06 / CONTACT</div><h2 className="relative mt-5 text-5xl font-extrabold tracking-[-.04em] sm:text-7xl">Have an idea?<br/><span className="gradient-text">Let's build it.</span></h2><p className="relative mx-auto mt-6 max-w-xl text-sm leading-7 text-zinc-400 sm:text-base">Whether you have a product idea, website, or creative experiment, let's turn it into something real.</p><div className="relative mt-8 flex justify-center"><Button href="mailto:hello@example.com">Start a Project</Button></div><div className="relative mt-10 flex justify-center gap-5 text-zinc-500"><a aria-label="GitHub" href="#"><Github size={18}/></a><a aria-label="LinkedIn" href="#"><Linkedin size={18}/></a><a aria-label="Instagram" href="#"><Instagram size={18}/></a><a aria-label="Email" href="mailto:hello@example.com"><Mail size={18}/></a></div></Reveal></div></div></section><footer className="border-t border-white/[.06] py-8"><div className="container flex flex-col justify-between gap-3 text-xs text-zinc-600 sm:flex-row"><span>© 2026 YOUR NAME. Built with intent.</span><span className="mono">NEXT.JS / TYPESCRIPT / MOTION</span></div></footer></main>}
